### ISSUE TITLE
Why is TabbedDemoImpl a generic class

### ISSUE THREAD

**Issue by javier-godoy** [FlowingCode/CommonsDemo#3]
What is the purpose of this type parameter?
https://github.com/FlowingCode/CommonsDemo/blob/941f86183210bc50d501efb912b425f36a9a8aa3/src/main/java/com/flowingcode/vaadin/addons/demo/impl/TabbedDemoImpl.java#L36

**Comment by ngonzalezpazFC** [comment]
That is because the demo is added to the layout (SplitLayout or VerticalLayout), thus restricting the demo type.

**Comment by javier-godoy** [comment]
What does it actually restrict? Looking at OrgChart demo it seems it serves no purpose. https://github.com/FlowingCode/OrgChartAddon/blob/3fc3b5886fe4c70d505cd9ef2ace2d2cd693af8b/src/test/java/com/flowingcode/vaadin/addons/orgchart/OrgchartDemoView.java#L42-L44

**Comment by ngonzalezpazFC** [comment]
All the demos extends from VerticalLayout

**Comment by ngonzalezpazFC** [comment]
I thought that maybe some demo could not extend from Component, so the tabbedDemo view would not work

**Comment by javier-godoy** [comment]
Right, the `demo` parameter must be a `Component`, but why is the class parameterized? I think that `TabbedDemoImpl(Component demo, String name, String sourceCodeUrl)` should suffice. More so, I'm not sure if the constructor should take any parameter at all, since the first demo (which is the constructor argument) isn't special in any way. 

I envision the following API
```
TabbedDemoImpl orgDemo = new TabbedDemoImpl();
orgDemo.addDemo(new DragAndDropExportDemo(), DRAGNDROP_DEMO, DRAGNDROP_SOURCE);
orgDemo.addDemo(new BottomTopDemo(), BOTTOMTOP_DEMO, BOTTOMTOP_SOURCE);
```

Instead of:

```
TabbedDemoImpl<DragAndDropExportDemo> orgDemo = new TabbedDemoImpl<>(new DragAndDropExportDemo(),
				DRAGNDROP_DEMO, DRAGNDROP_SOURCE);
		orgDemo.addDemo(new BottomTopDemo(), BOTTOMTOP_DEMO, BOTTOMTOP_SOURCE);
```

What do you think?

**Comment by ngonzalezpazFC** [comment]
Now I understand. I think it is better with your suggested changes!
