### ISSUE TITLE
Add support for just one way of specifying @DemoSource

### ISSUE THREAD

**Issue by mlopezFC** [FlowingCode/CommonsDemo#51]
It would be nice to have one way of specifying the sources so they work in production and development mode.

**Comment by javier-godoy** [comment]
Good point. `@DemoSource` defaults to the source of the annotated class (from the linked repository or, in development mode, from the local sources). However that breaks if you specify `src/test/...` because production mode expects a URL (and a URL in dev mode won't fetch the local source).
