### ISSUE TITLE
Problem with showing route in the sources view

### ISSUE THREAD

**Issue by mlopezFC** [FlowingCode/CommonsDemo#54]
Basically [this](https://github.com/FlowingCode/ExtendedLoginAddon/blob/master/src/test/java/com/flowingcode/vaadin/addons/extendedlogin/TestLoginLayoutView.java#L38) is not being shown.

```
@Route(value = "extended-login/login-layout", layout = TestLoginLayout.class)
// show-source @Route("value = "extended-login/login-layout-demo", layout = ExtendedLoginDemoView.class)
```

**Comment by javier-godoy** [comment]
`map` should apply _after_ `filter` (if a line is explicitly added with `show-source` it must not be filtered)
https://github.com/FlowingCode/CommonsDemo/blob/728f29ed08cce4d2cb74ac464f2fee0ba71e408b/src/main/resources/META-INF/resources/frontend/code-viewer.ts#L296-L301
